### ISSUE TITLE
Typo in playerPlays.py

### ISSUE THREAD

**Issue by rmcguffee** [tvanpat/cli-battleship#1]
Cool project and excited to see FastAPI & MongoDB integrated down the line! 

My issue is super minor. Just need a space on line 64 or line 65 of playerPlays.py. 

Right now asks if we want to "print theprobability matrix" because the strings are on different lines.

![image](https://user-images.githubusercontent.com/16456706/126907737-b56cc2ab-3d5f-4611-b032-42de0cf4a586.jpeg)

If you're open to collaborators, I'm happy to branch and send pull requests on quick hit things like this in the future?

**Comment by tvanpat** [comment]
Fixed, thanks for the note.
